package xyz.mattyb.khance.enums

enum class TldType {
    BRAND,
    COUNTRY,
    GENERIC,
    GENERIC_CHINESE,
    GENERIC_FRENCH,
    GENERIC_GERMAN,
    GENERIC_HINDI,
    GENERIC_ITALIAN,
    GENERIC_PORTUGUESE,
    GENERIC_SPANISH,
    GEOGRAPHIC_AFRICA,
    GEOGRAPHIC_ASIA,
    GEOGRAPHIC_EUROPE,
    GEOGRAPHIC_NORTH_AMERICA,
    GEOGRAPHIC_OCEANIA,
    GEOGRAPHIC_SOUTH_AMERICA,
    ORIGINAL,
    SPECIAL_USE
    ;
}